### ISSUE TITLE
[Bug]: Video meta file removal is unreliable again

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#2768]
### Guidelines

- [ ] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Some video meta files aren't removed with the video meta file removal option checked.
Same as #1562. It was fixed but is happening again, though rarely, since a few versions.

### Expected Behavior

All video meta files are always removed.

### Issue Labels

inconsistent behavior

### FreeTube Version

0.17.1-nightly-2189

### Operating System Version

Windows 11 22H2

### Installation Method

Portable

### Primary API used

Local API

### Additional Information

See #1562.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
I'm guessing that you close FreeTube while you are on the video page?
