### ISSUE TITLE
[Feature Request]: login with youtube for personalized suggestions and potential tracking

### ISSUE THREAD

**Issue by alidan** [FreeTubeApp/FreeTube#5786]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I am either not able to find it or im searching the wrong things.

I'm going to be honest, I am almost completely beyond caring about privacy at this point with certain things, youtube seeing what I watch being a major one. I have been looking for a way to not watch youtube in my browser, because youtube eats a crapload of ram. let me describe my issue, I see a video I like, I open it in a new tab, along with several other ones, and after a while chrome is eating 27gb of ram with near 20 of it belonging to youtube tabs. whatever is wrong in my head that compels me to do this isn't fixable. bookmarking doesn't work because bookmarking just means I repeat the exact same actions with the exact same videos.

This program is near perfect for my need, 1 video will be open and play, it remembers the time on videos so if I need to go to some other one or decided to watch it later it remembers, but a lot of the people I find i find though the recommendations after it sees what I like/am currently interested in.

### Proposed Solution

I'm not saying everyone needs to log into google, but it would be nice to be able to, so what I do in that program translates to what's in the browser, so that the recommendations on a video I watch tangentially relate to that video or my interests, in browser, 17 of the 18 are videos I would want to watch later on, in program, with the same number of recommended videos, every single one was some main stream media, fox news, msnbc, bloomberg, nbc, local (not my local) affiliate, hell I went to another video to see if it changed, something not current events, and the recommendations seem to be more or less just as bad. 

### Alternatives Considered

I have tried for YEARS to find anything like this but every time its the same issue, I either need to use the browser which means its not going to get used for long, it doesn't track what I do in the browser when I find the videos so youtube keeps serving me the exact same videos or telling me they were never watched, or the thing is web based and does nothing a youtube page won't already do. this is the only option that is nearly everything I could hope for, the runner up is importing videos to potplayer playlists, but it doesn't track if a video has been seen in the player.

### Issue Labels

improvement to existing feature

### Additional Information

If this is a non starter and would never be considered, do you happen to know of ANY other alternative close to what I want/need?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/2959
